### ISSUE TITLE
Apple Calendar Issue

### ISSUE THREAD

**Issue by tempus2016** [kdw2060/hassio-addons#10]
Trying to get this working with my icloud calendar but keep getting this error:
```
Previously stored events posted to sensor(s) at: Sat Apr 02 2022 13:49:09 GMT+0100 (British Summer Time)
Calendar(s) queried at: Sat Apr 02 2022 14:04:00 GMT+0100 (British Summer Time)
axios error: getaddrinfo ENOTFOUND p45.icloud.comundefined
Events posted to sensor(s) at: Sat Apr 02 2022 14:06:00 GMT+0100 (British Summer Time)
```

I get this before it tries to download the calendar update:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 29s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
```

This is my config:
```
calendarList:
  - calName: worktest
    calType: caldav
    locale: en-gb
    username: ****
    password: ****
    caldavUrl: https://p**-caldav.icloud.com/*********/calendars/Lou Work
```
