### ISSUE TITLE
Baikal sync not working

### ISSUE THREAD

**Issue by ronschaeffer** [kdw2060/hassio-addons#12]
Thanks very much for the add on. I am trying to it working with self hosted Baikal without success. I can sync with the Baikal calendar using desktop applications like 1Calendar.

Add on log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 7s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
error: Request failed with status code 500[object Object]
Calendar(s) queried at: Tue Apr 12 2022 11:00:00 GMT+0100 (British Summer Time)
postEventsAllCalendars error: TypeError: Cannot read property 'length' of undefined
CRON-Task: Events posted to sensor(s) at: Tue Apr 12 2022 11:00:00 GMT+0100 (British Summer Time)
```

Nothing at all appears in the Baikal log. 

I noticed that with version 0.200 support for Baikal calldav calendars is added. Presumably that means that the following from the docs no longer applies:  "The add-on uses the jcal format querying the server. Make sure this plugin is installed in your Baikal instance. See [Baikal Plugin Info](https://sabre.io/dav/ics-export-plugin/) for more information."

Add on configuration:
```
locale: en-gb
fetchDays: 365
fetchCRON: '*/30 * * * *'
calendarList:
  - calName: twickenhamevent
    calType: baikal
    username: xxxxx
    password: xxxxx
    caldavUrl: http://xxx.xxx.xxx.xxx:xxxx/dav.php/calendars/136worple/twickenhamevent
```
One thing I notice versus the  documentation is that I'm not using SSL whereas the documenation notes using an https address.

Any ideas? Thank you.

**Comment by ronschaeffer** [comment]
Server and plug-in info [here](https://1drv.ms/u/s!AtYGFztGDGYlkq1Thmm68SyqzunBiA?e=3FwPGJ)

**Comment by kdw2060** [comment]
Hi, no those docs were updated for version 0.200 and that information is new since then. Thus for Baikal that plugin is required, because the parsing of the data depends on it.

But the error log show a status code 500 error, which suggests another issue. That's an error you get when an endpoint (your caldav server) sends 'internal server error'. For starters i'd try an https url. 
If that doesn't work: I don't run Baikal myself and have no experience with it. User [@cellerich](https://github.com/cellerich) wrote that code and can probably help you better to debug the issue.

**Comment by cellerich** [comment]
Hi Ron

Just noticed that you have the `locale:` keyword in the wrong position. It belongs to the calendar:

```yaml
fetchDays: 365
fetchCRON: '*/30 * * * *'
calendarList:
  - calName: twickenhamevent
    calType: baikal
    locale: en-gb
    username: xxxxx
    password: xxxxx
    caldavUrl: http://xxx.xxx.xxx.xxx:xxxx/dav.php/calendars/136worple/twickenhamevent
```

And like @kdw2060 mentioned, the Baikal `jcal-query` plugin is needed!
