### ISSUE TITLE
Content after colon in description attribute not added to sensor

### ISSUE THREAD

**Issue by ronschaeffer** [kdw2060/hassio-addons#13]
Hass Calendar Addon version: 0.200
Home Assistant Core: 2022.4.2
calType:  caldav

I don't know if this is a bug or a limitation of caldav. I have events which have colons in the description field. Anything that comes after the colon in the description field is not picked up in the associated sensor attribute.

In the example below, the first event has `14:00 Army v Navy` in the description field, but only `14` appears in the attribute. For the second event, I removed the colon so that the description reads `1400 Army v Navy`, and the entire description field is picked up in the sensor attribute.

```
data:
  - description: '14'
    startDate: '2022-05-01T13:00:00.000Z'
    endDate: '2022-04-30T13:05:00.000Z'
    location: ''
    summary: Rugby Parking
    year: 22
    start_month: Apr
    start_month_digits: 4
    start_day: 30
    start_time: '14:00'
    end_month: Apr
    end_month_digits: 4
    end_day: 30
    end_time: '14:05'
  - description: 1400 Army v Navy
    startDate: '2022-05-01T13:00:00.000Z'
    endDate: '2022-04-30T13:05:00.000Z'
    location: ''
    summary: Rugby Parking - No colon
    year: 22
    start_month: Apr
    start_month_digits: 4
    start_day: 30
    start_time: '14:00'
    end_month: Apr
    end_month_digits: 4
    end_day: 30
    end_time: '14:05'
```
