### ISSUE TITLE
Icloud caldav error

### ISSUE THREAD

**Issue by compoundbow83** [kdw2060/hassio-addons#19]
Hello,
I wanted to connect an icloud calendar but I get the following error:

axios error: Request failed with status code 403[object Object]
Calendar(s) queried at: Sat Jun 04 2022 14:00:00 GMT+0200 (Central European Summer Time)
postEventsAllCalendars error: TypeError: Cannot read properties of undefined (reading 'length')
CRON-Task: Events posted to sensor(s) at: Sat Jun 04 2022 14:00:00 GMT+0200 (Central European Summer Time)

My configuration looks so:
```
locale: nl-be
fetchDays: 365
fetchCRON: '*/30 * * * *'
calendarList:
  - calName: Familie
    calType: caldav
    username: myicloudusername
    password: specific password
    caldavUrl: https://pxx-caldav.icloud.com/xxxxxxxxxxxxxxxxxx/calendars/archery/
```

I found out the URL via the icloud calendar. I published my calendar for a short time and it showed the parts for the URL

What make I wrong?
