### ISSUE TITLE
[tutorial] how to setup NextCloud caldav calendar

### ISSUE THREAD

**Issue by thundergreen** [kdw2060/hassio-addons#7]
I am trying to setup the nectcloud caldav with this addon but won't get it work.
My config is:

```
calendarList:
  - calName: appointments
    calType: caldav
    locale: fr
    username: thorsten
    password: '%%xxxxxx%%'
    caldavUrl: https://cloud-space.ddns.net/remote.php/dav
```

Logs show only:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 8s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities```

**Comment by thundergreen** [comment]
No it creates a sensor but data is empty.
logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
added 62 packages, and audited 63 packages in 7s
21 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Previously stored events posted to sensor(s) at: Wed Feb 02 2022 21:11:22 GMT+0100 (Central European Standard Time)
```

my config:

```
calendarList:
  - calName: appointments
    calType: caldav
    locale: nl-be
    username: thorsten
    password: '%password%'
    caldavUrl: https://cloud-space.ddns.net/remote.php/dav/calendars/thorsten/birthdays/
```
